### ISSUE TITLE
FID eval unnormal

### ISSUE THREAD

**Issue by zhoujiawei3** [SenseTime-FVG/OpenDWM#31]
When I try to evaluate unimlvg's fid and fvd, the value of fvd is 34.757, which is close to that in the pape. However, when I evaluate the fid, the value is 481.513. I believe there is something wrong with my config setting, can you help me to figure out where is my mistake. The whole json is as follow
```json
{
    "device": "cuda",
    "ddp_backend": "nccl",
    "train_epochs": 6,
    "generator_seed": 0,
    "data_shuffle": true,
    "fix_training_data_order": true,
    "global_state": {
        "nuscenes_fs": {
            "_class_name": "dwm.fs.czip.CombinedZipFileSystem",
            "fs": {
                "_class_name": "dwm.fs.dirfs.DirFileSystem",
                "path": "/data2/zhoujiawei"
                        
            },
            "paths": [
                "nuscenes/v1.0-trainval-zip/interp_12Hz_trainval.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval01_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval02_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval03_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval04_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval05_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval06_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval07_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval08_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval09_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval10_blobs.zip",
                "nuscenes/v1.0-trainval-zip/nuScenes-map-expansion-v1.3.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval.zip"
            ]
        },
        "device_mesh": {
            "_class_name": "torch.distributed.device_mesh.init_device_mesh",
            "device_type": "cuda",
            "mesh_shape": [
                1,
                2
            ]
        }
    },
    "optimizer": {
        "_class_name": "torch.optim.AdamW",
        "lr": 8e-5
    },
    "pipeline": {
        "_class_name": "dwm.pipelines.ctsd.CrossviewTemporalSD",
        "common_config": {
            "frame_prediction_style": "ctsd",
            "cat_condition": true,
            "cond_with_action": false,
            "condition_on_all_frames": true,
            "explicit_view_modeling": true,
            "distribution_framework": "fsdp",
            "ddp_wrapper_settings": {
                "sharding_strategy": {
                    "_class_name": "torch.distributed.fsdp.ShardingStrategy",
                    "value": 4
                },
                "device_mesh": {
                    "_class_name": "dwm.common.get_state",
                    "key": "device_mesh"
                },
                "auto_wrap_policy": {
                    "_class_name": "torch.distributed.fsdp.wrap.ModuleWrapPolicy",
                    "module_classes": [
                        {
                            "_class_name": "get_class",
                            "class_name": "diffusers.models.attention.JointTransformerBlock"
                        },
                        {
                            "_class_name": "get_class",
                            "class_name": "dwm.models.crossview_temporal.VTSelfAttentionBlock"
                        }
                    ]
                },
                "mixed_precision": {
                    "_class_name": "torch.distributed.fsdp.MixedPrecision",
                    "param_dtype": {
                        "_class_name": "get_class",
                        "class_name": "torch.float16"
                    }
                }
            },
            "t5_fsdp_wrapper_settings": {
                "sharding_strategy": {
                    "_class_name": "torch.distributed.fsdp.ShardingStrategy",
                    "value": 4
                },
                "device_mesh": {
                    "_class_name": "dwm.common.get_state",
                    "key": "device_mesh"
                },
                "auto_wrap_policy": {
                    "_class_name": "torch.distributed.fsdp.wrap.ModuleWrapPolicy",
                    "module_classes": [
                        {
                            "_class_name": "get_class",
                            "class_name": "transformers.models.t5.modeling_t5.T5Block"
                        }
                    ]
                }
            },
            "text_encoder_load_args": {
                "torch_dtype": {
                    "_class_name": "get_class",
                    "class_name": "torch.float16"
                }
            },
            "memory_efficient_batch": 12
        },
        "training_config": {
            "text_prompt_condition_ratio": 0.8,
            "3dbox_condition_ratio": 0.8,
            "hdmap_condition_ratio": 0.8,
            "explicit_view_modeling_ratio": 0.8,
            "reference_frame_count": 3,
            "generation_task_ratio": 0.2,
            "image_generation_ratio": 0.5,
            "all_reference_visible_ratio": 0.8,
            "reference_visible_rate": 0.5,
            "disable_reference_frame_loss": true,
            "enable_grad_scaler": true
        },
        "inference_config": {
            "guidance_scale": 3,
            "inference_steps": 50,
            "preview_image_size": [
                448,
                252
            ],
            "evaluation_item_count": 480
        },
        "model": {
            "_class_name": "dwm.models.crossview_temporal_dit.DiTCrossviewTemporalConditionModel",
            "attention_head_dim": 64,
            "caption_projection_dim": 1536,
            "in_channels": 16,
            "joint_attention_dim": 4096,
            "num_attention_heads": 24,
            "num_layers": 24,
            "out_channels": 16,
            "patch_size": 2,
            "pooled_projection_dim": 2048,
            "pos_embed_max_size": 192,
            "sample_size": 128,
            "perspective_modeling_type": "explicit",
            "enable_crossview": true,
            "crossview_attention_type": "rowwise",
            "crossview_block_layers": [
                1,
                5,
                9,
                13,
                17,
                21
            ],
            "crossview_gradient_checkpointing": true,
            "enable_temporal": true,
            "temporal_attention_type": "full",
            "temporal_block_layers": [
                1,
                5,
                9,
                13,
                17,
                21
            ],
            "temporal_gradient_checkpointing": true,
            "mixer_type": "AlphaBlender",
            "merge_factor": 2,
            "condition_image_adapter_config": {
                "in_channels": 6,
                "channels": [
                    1536,
                    1536,
                    1536,
                    1536,
                    1536,
                    1536
                ],
                "is_downblocks": [
                    true,
                    false,
                    false,
                    false,
                    false,
                    false
                ],
                "num_res_blocks": 2,
                "downscale_factor": 8,
                "use_zero_convs": true
            }
        },
        "pretrained_model_name_or_path": "/data/Diffusion_models/stable-diffusion-3-medium-diffusers",
        "model_checkpoint_path": "/data3/zhoujiawei/dfmodel/openDWM/UniMVLG/ctsd_unimlvg_tirda_bm_nwa_60k.pth",
        "metrics": {
            "fid": {
                "_class_name": "torchmetrics.image.fid.FrechetInceptionDistance",
                "normalize": true
            }
        }
    },
    "validation_dataset": {
        "_class_name": "dwm.datasets.common.DatasetAdapter",
        "base_dataset": {
            "_class_name": "torch.utils.data.ConcatDataset",
            "datasets": [
                {
                    "_class_name": "dwm.datasets.nuscenes.MotionDataset",
                    "fs": {
                        "_class_name": "dwm.common.get_state",
                        "key": "nuscenes_fs"
                    },
                    "dataset_name": "v1.0-trainval",
                    "split": "val",
                    "sequence_length": 1,
                    "fps_stride_tuples": [
                        [
                            0,
                            3
                        ]
                    ],
                    "sensor_channels": [
                        "LIDAR_TOP",
                        "CAM_FRONT_LEFT",
                        "CAM_FRONT",
                        "CAM_FRONT_RIGHT",
                        "CAM_BACK_RIGHT",
                        "CAM_BACK",
                        "CAM_BACK_LEFT"
                    ],
                    "keyframe_only": true,
                    "enable_synchronization_check": false,
                    "enable_camera_transforms": true,
                    "enable_ego_transforms": true,
                    "_3dbox_image_settings": {},
                    "hdmap_image_settings": {},
                    "image_description_settings": {
                        "path": "/home/zhoujiawei/OpenDWM/text_description/nuscenes/nuscenes_v1.0-trainval_caption_v2_val.json",
                        "time_list_dict_path": "/home/zhoujiawei/OpenDWM/text_description/nuscenes/nuscenes_v1.0-trainval_caption_v2_times_val.json",
                        "align_keys": [
                            "time",
                            "weather"
                        ]
                    },
                    "stub_key_data_dict": {
                        "crossview_mask": [
                            "content",
                            {
                                "_class_name": "torch.tensor",
                                "data": {
                                    "_class_name": "json.loads",
                                    "s": "[[1,1,0,0,0,1],[1,1,1,0,0,0],[0,1,1,1,0,0],[0,0,1,1,1,0],[0,0,0,1,1,1],[1,0,0,0,1,1]]"
                                },
                                "dtype": {
                                    "_class_name": "get_class",
                                    "class_name": "torch.bool"
                                }
                            }
                        ]
                    }
                }
            ]
        },
        "transform_list": [
            {
                "old_key": "images",
                "new_key": "vae_images",
                "transform": {
                    "_class_name": "torchvision.transforms.Compose",
                    "transforms": [
                        {
                            "_class_name": "torchvision.transforms.Resize",
                            "size": [
                                256,
                                448
                            ]
                        },
                        {
                            "_class_name": "torchvision.transforms.ToTensor"
                        }
                    ]
                }
            },
            {
                "old_key": "3dbox_images",
                "new_key": "3dbox_images",
                "transform": {
                    "_class_name": "torchvision.transforms.Compose",
                    "transforms": [
                        {
                            "_class_name": "torchvision.transforms.Resize",
                            "size": [
                                256,
                                448
                            ]
                        },
                        {
                            "_class_name": "torchvision.transforms.ToTensor"
                        }
                    ]
                }
            },
            {
                "old_key": "hdmap_images",
                "new_key": "hdmap_images",
                "transform": {
                    "_class_name": "torchvision.transforms.Compose",
                    "transforms": [
                        {
                            "_class_name": "torchvision.transforms.Resize",
                            "size": [
                                256,
                                448
                            ]
                        },
                        {
                            "_class_name": "torchvision.transforms.ToTensor"
                        }
                    ]
                }
            },
            {
                "old_key": "image_description",
                "new_key": "clip_text",
                "transform": {
                    "_class_name": "dwm.datasets.common.Copy"
                },
                "stack": false
            }
        ],
        "pop_list": [
            "images",
            "lidar_points",
            "image_description"
        ]
    },
    "validation_dataloader": {
        "batch_size": 1,
        "num_workers": 1,
        "prefetch_factor": 3,
        "collate_fn": {
            "_class_name": "dwm.datasets.common.CollateFnIgnoring",
            "keys": [
                "clip_text"
            ]
        },
        "persistent_workers": true
    },
    "preview_dataloader": {
        "batch_size": 1,
        "num_workers": 1,
        "prefetch_factor": 1,
        "shuffle": true,
        "drop_last": true,
        "collate_fn": {
            "_class_name": "dwm.datasets.common.CollateFnIgnoring",
            "keys": [
                "clip_text"
            ]
        },
        "persistent_workers": true
    },
    "informations": {
        "fid": 3.34,
        "fvd": 18.76,
        "fvd_on_nusc_by_3_ref_frames": 36.10,
        "fvd_on_nusc_by_1_ref_frame": 41.41,
        "fvd_on_nusc_without_ref_frame": 106.01,
        "total_batch_sizes": 32,
        "steps": 60000
    }
}
```
The total output is here:
```bash
(openDWM) zhoujiawei@uubn:~/OpenDWM$ CUDA_VISIBLE_DEVICES=6,7 OMP_NUM_THREADS=1 TOKENIZERS_PARALLELISM=false PYTHONPATH=src:externals/waymo-open-dataset/src:externals/TATS/tats/fvd python -m torch.distributed.run --nnodes "1" --nproc-per-node "2" --node-rank "0" --master-addr "127.0.0.1" --master-port "12397" src/dwm/evaluate.py -c /home/zhoujiawei/OpenDWM/configs/ctsd/unimlvg/ctsd_unimlvg_stage3_tirda_bm_nwa_eval_fid.json -o /data3/zhoujiawei/OpenDWM_out
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.41s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.42s/it]
3346.1 M parameters are trainable.
The pipeline is loaded.
The validation dataset is loaded with 2082 items.
[rank0]:[W411 22:27:56.402917316 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank1]:[W411 22:27:56.410622143 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
Step 0, fid: 481.513
[rank1]:[W411 22:28:01.587579769 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[rank0]:[W411 22:28:01.983618811 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
```

**Comment by wzhgba** [comment]
The FID in the UniMLVG paper is evaluated under the generated images from the video generation task, so you can directly add `torchmetrics.image.fid.FrechetInceptionDistance` to the metrics while evaluating the FVD.
Your current JSON config is mainly to evaluate an image generation model (T2I task).

**Comment by zhoujiawei3** [comment]
The problem is solved. Thanks for your help

**Comment by zhoujiawei3** [comment]
@wzhgba 您好，我想请问您unimlvg模型不支持图像生成吗？在如上的T2I实验中fid显著的高，除此以外，我在进行image generation task的时候，模型的输出几乎是乱码

<img width="847" height="477" alt="Image" src="https://github.com/user-attachments/assets/171eeedb-2f97-4661-a702-0c7b3165712f" />

我的生成config和代码附在下方了
```json
{
    "device": "cuda",
    "ddp_backend": "nccl",
    "train_epochs": 6,
    "generator_seed": 0,
    "data_shuffle": true,
    "fix_training_data_order": true,
    "global_state": {
        "nuscenes_fs": {
            "_class_name": "dwm.fs.czip.CombinedZipFileSystem",
            "fs": {
                "_class_name": "dwm.fs.dirfs.DirFileSystem",
                "path": "/data2/zhoujiawei/"
            },
            "paths": [
                "nuscenes/v1.0-trainval-zip/v1.0-trainval01_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval02_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval03_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval04_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval05_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval06_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval07_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval08_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval09_blobs.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval10_blobs.zip",
                "nuscenes/v1.0-trainval-zip/nuScenes-map-expansion-v1.3.zip",
                "nuscenes/v1.0-trainval-zip/v1.0-trainval.zip"

            ]
        },
        "device_mesh": {
            "_class_name": "torch.distributed.device_mesh.init_device_mesh",
            "device_type": "cuda",
            "mesh_shape": [
                1,
                1
            ]
        }
    },
    "optimizer": {
        "_class_name": "torch.optim.AdamW",
        "lr": 8e-5
    },
    "pipeline": {
        "_class_name": "dwm.pipelines.ctsd.CrossviewTemporalSD",
        "common_config": {
            "frame_prediction_style": "ctsd",
            "cat_condition": true,
            "cond_with_action": false,
            "condition_on_all_frames": true,
            "explicit_view_modeling": true,
            "distribution_framework": "fsdp",
            "ddp_wrapper_settings": {
                "sharding_strategy": {
                    "_class_name": "torch.distributed.fsdp.ShardingStrategy",
                    "value": 4
                },
                "device_mesh": {
                    "_class_name": "dwm.common.get_state",
                    "key": "device_mesh"
                },
                "auto_wrap_policy": {
                    "_class_name": "torch.distributed.fsdp.wrap.ModuleWrapPolicy",
                    "module_classes": [
                        {
                            "_class_name": "get_class",
                            "class_name": "diffusers.models.attention.JointTransformerBlock"
                        },
                        {
                            "_class_name": "get_class",
                            "class_name": "dwm.models.crossview_temporal.VTSelfAttentionBlock"
                        }
                    ]
                },
                "mixed_precision": {
                    "_class_name": "torch.distributed.fsdp.MixedPrecision",
                    "param_dtype": {
                        "_class_name": "get_class",
                        "class_name": "torch.float16"
                    }
                }
            },
            "t5_fsdp_wrapper_settings": {
                "sharding_strategy": {
                    "_class_name": "torch.distributed.fsdp.ShardingStrategy",
                    "value": 4
                },
                "device_mesh": {
                    "_class_name": "dwm.common.get_state",
                    "key": "device_mesh"
                },
                "auto_wrap_policy": {
                    "_class_name": "torch.distributed.fsdp.wrap.ModuleWrapPolicy",
                    "module_classes": [
                        {
                            "_class_name": "get_class",
                            "class_name": "transformers.models.t5.modeling_t5.T5Block"
                        }
                    ]
                }
            },
            "text_encoder_load_args": {
                "torch_dtype": {
                    "_class_name": "get_class",
                    "class_name": "torch.float16"
                }
            },
            "memory_efficient_batch": 12
        },
        "training_config": {
            "text_prompt_condition_ratio": 0.8,
            "3dbox_condition_ratio": 0.8,
            "hdmap_condition_ratio": 0.8,
            "explicit_view_modeling_ratio": 0.8,
            "reference_frame_count": 3,
            "generation_task_ratio": 0.2,
            "image_generation_ratio": 0.5,
            "all_reference_visible_ratio": 0.8,
            "reference_visible_rate": 0.5,
            "disable_reference_frame_loss": true,
            "enable_grad_scaler": true
        },
        "inference_config": {
            "guidance_scale": 3,
            "inference_steps": 50,
            "preview_image_size": [
                448,
                252
            ],
            "evaluation_item_count": 480
        },
        "model": {
            "_class_name": "dwm.models.crossview_temporal_dit.DiTCrossviewTemporalConditionModel",
            "attention_head_dim": 64,
            "caption_projection_dim": 1536,
            "in_channels": 16,
            "joint_attention_dim": 4096,
            "num_attention_heads": 24,
            "num_layers": 24,
            "out_channels": 16,
            "patch_size": 2,
            "pooled_projection_dim": 2048,
            "pos_embed_max_size": 192,
            "sample_size": 128,
            "perspective_modeling_type": "explicit",
            "enable_crossview": true,
            "crossview_attention_type": "rowwise",
            "crossview_block_layers": [
                1,
                5,
                9,
                13,
                17,
                21
            ],
            "crossview_gradient_checkpointing": true,
            "enable_temporal": true,
            "temporal_attention_type": "full",
            "temporal_block_layers": [
                1,
                5,
                9,
                13,
                17,
                21
            ],
            "temporal_gradient_checkpointing": true,
            "mixer_type": "AlphaBlender",
            "merge_factor": 2,
            "condition_image_adapter_config": {
                "in_channels": 6,
                "channels": [
                    1536,
                    1536,
                    1536,
                    1536,
                    1536,
                    1536
                ],
                "is_downblocks": [
                    true,
                    false,
                    false,
                    false,
                    false,
                    false
                ],
                "num_res_blocks": 2,
                "downscale_factor": 8,
                "use_zero_convs": true
            }
        },
        "pretrained_model_name_or_path": "/data/Diffusion_models/stable-diffusion-3-medium-diffusers",
        "model_checkpoint_path": "/data3/zhoujiawei/dfmodel/openDWM/UniMVLG/ctsd_unimlvg_tirda_bm_nwa_60k.pth",
        "metrics": {
            "fid": {
                "_class_name": "torchmetrics.image.fid.FrechetInceptionDistance",
                "normalize": true
            },
            "fvd": {
                "_class_name": "dwm.metrics.fvd.FrechetVideoDistance",
                "inception_3d_checkpoint_path": "/home/zhoujiawei/OpenDWM/externals/TATS/tats/fvd/i3d_pretrained_400.pt",
                "sequence_count": 106
            }
        }
    },
    "validation_dataset": {
        "_class_name": "dwm.datasets.common.DatasetAdapter",
        "base_dataset": {
            "_class_name": "torch.utils.data.ConcatDataset",
            "datasets": [
                {
                    "_class_name": "dwm.datasets.nuscenes.MotionDataset",
                    "enable_scene_description": true,
                    "fs": {
                        "_class_name": "dwm.common.get_state",
                        "key": "nuscenes_fs"
                    },
                    "dataset_name": "v1.0-trainval",
                    "sequence_length": 1,
                    "fps_stride_tuples": [
                        [
                            0,
                            1000
                        ]
                    ],
                    "sensor_channels": [
                        "LIDAR_TOP",
                        "CAM_FRONT_LEFT",
                        "CAM_FRONT",
                        "CAM_FRONT_RIGHT",
                        "CAM_BACK_RIGHT",
                        "CAM_BACK",
                        "CAM_BACK_LEFT"
                    ],
                    "keyframe_only": true,
                    "enable_synchronization_check": false,
                    "enable_camera_transforms": true,
                    "enable_ego_transforms": true,
                    "enable_sample_data":true,
                    "_3dbox_image_settings": {},
                    "hdmap_image_settings": {},
                    "stub_key_data_dict": {
                        "crossview_mask": [
                            "content",
                            {
                                "_class_name": "torch.tensor",
                                "data": {
                                    "_class_name": "json.loads",
                                    "s": "[[1,1,0,0,0,1],[1,1,1,0,0,0],[0,1,1,1,0,0],[0,0,1,1,1,0],[0,0,0,1,1,1],[1,0,0,0,1,1]]"
                                },
                                "dtype": {
                                    "_class_name": "get_class",
                                    "class_name": "torch.bool"
                                }
                            }
                        ]
                    }
                }
            ]
        },
        "transform_list": [
            {
                "old_key": "images",
                "new_key": "vae_images",
                "transform": {
                    "_class_name": "torchvision.transforms.Compose",
                    "transforms": [
                        {
                            "_class_name": "torchvision.transforms.Resize",
                            "size": [
                                256,
                                448
                            ]
                        },
                        {
                            "_class_name": "torchvision.transforms.ToTensor"
                        }
                    ]
                }
            },
            {
                "old_key": "3dbox_images",
                "new_key": "3dbox_images",
                "transform": {
                    "_class_name": "torchvision.transforms.Compose",
                    "transforms": [
                        {
                            "_class_name": "torchvision.transforms.Resize",
                            "size": [
                                256,
                                448
                            ]
                        },
                        {
                            "_class_name": "torchvision.transforms.ToTensor"
                        }
                    ]
                }
            },
            {
                "old_key": "hdmap_images",
                "new_key": "hdmap_images",
                "transform": {
                    "_class_name": "torchvision.transforms.Compose",
                    "transforms": [
                        {
                            "_class_name": "torchvision.transforms.Resize",
                            "size": [
                                256,
                                448
                            ]
                        },
                        {
                            "_class_name": "torchvision.transforms.ToTensor"
                        }
                    ]
                }
            },
            {
                "old_key": "scene_description",
                "new_key": "clip_text",
                "transform": {
                    "_class_name": "dwm.datasets.common.Copy"
                },
                "stack": false
            }
        ],
        "pop_list": [
            "images",
            "lidar_points",
            "scene_description"
        ]
    },
    "validation_dataloader": {
        "batch_size": 1,
        "num_workers": 1,
        "prefetch_factor": 3,
        "collate_fn": {
            "_class_name": "dwm.datasets.common.CollateFnIgnoring",
            "keys": [
                "clip_text",
                "sample_data"
            ]
        },
        "persistent_workers": true
    },
    "preview_dataloader": {
        "batch_size": 1,
        "num_workers": 1,
        "prefetch_factor": 1,
        "shuffle": true,
        "drop_last": true,
        "collate_fn": {
            "_class_name": "dwm.datasets.common.CollateFnIgnoring",
            "keys": [
                "clip_text",
                "sample_data"
            ]
        },
        "persistent_workers": true
    },
    "informations": {
        "fid": 3.34,
        "fvd": 18.76,
        "fvd_on_nusc_by_3_ref_frames": 36.10,
        "fvd_on_nusc_by_1_ref_frame": 41.41,
        "fvd_on_nusc_without_ref_frame": 106.01,
        "total_batch_sizes": 32,
        "steps": 60000
    }
}
```

```python
import sys
sys.path.append('/home/zhoujiawei/OpenDWM/src')
sys.path.append('/home/zhoujiawei/OpenDWM/externals/TATS/tats/fvd')
import argparse
import dwm.common
import json
import numpy as np
import os
import torch
import diffusers
import torchvision
from PIL import Image
from tqdm import tqdm  # 添加tqdm导入

os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '12382'
os.environ['RANK'] = '0'
os.environ['WORLD_SIZE'] = '1'
os.environ['CUDA_VISIBLE_DEVICES'] = '6'

def create_parser():
    parser = argparse.ArgumentParser(
        description="The script to run the diffusion model to generate data for"
        "detection evaluation.")
    parser.add_argument(
        "-c", "--config-path", type=str, default='/home/zhoujiawei/OpenDWM/configs/unimlvg/generate_result_as_nuscenes_data_frame_generation_nuscenes.json',
        help="The config to load the train model and dataset.")
    parser.add_argument(
        "-o", "--output-path", type=str, default='/data3/zhoujiawei/carla_nuscenes_benchmark/test_benchmark_replace_first_frame_nuscenes',
        help="The path to save checkpoint files.")
    return parser


if __name__ == "__main__":
    parser = create_parser()
    args = parser.parse_args()

    with open(args.config_path, "r", encoding="utf-8") as f:
        config = json.load(f)
    inference_config= config["pipeline"]['inference_config']
    # set distributed training (if enabled), log, random number generator, and
    # load the checkpoint (if required).
    ddp = "LOCAL_RANK" in os.environ
    # ddp=False
    if ddp:
        local_rank = int(os.environ["LOCAL_RANK"])
        device = torch.device(config["device"], local_rank)
        if config["device"] == "cuda":
            torch.cuda.set_device(local_rank)

        torch.distributed.init_process_group(backend=config["ddp_backend"])
    else:
        device = torch.device(config["device"])

    # setup the global state
    if "global_state" in config:
        for key, value in config["global_state"].items():
            dwm.common.global_state[key] = \
                dwm.common.create_instance_from_config(value)

    should_log = (ddp and local_rank == 0) or not ddp
    # should_save = not torch.distributed.is_initialized() or \
    #     torch.distributed.get_rank() == 0
    

    pipeline = dwm.common.create_instance_from_config(
        config["pipeline"], output_path=args.output_path, config=config,
        device=device)
    if should_log:
        print("The pipeline is loaded.")

    # load the dataset
    validation_dataset = dwm.common.create_instance_from_config(
        config["validation_dataset"])
    vae=pipeline.vae
    if ddp:
        validation_datasampler = \
            torch.utils.data.distributed.DistributedSampler(
                validation_dataset)
        validation_dataloader = torch.utils.data.DataLoader(
            validation_dataset,
            **dwm.common.instantiate_config(config["validation_dataloader"]),
            sampler=validation_datasampler)
    else:
        validation_datasampler = None
        validation_dataloader = torch.utils.data.DataLoader(
            validation_dataset,
            **dwm.common.instantiate_config(config["validation_dataloader"]))

    if should_log:
        print("The validation dataset is loaded with {} items.".format(
            len(validation_dataset)))

    if ddp:
        validation_datasampler.set_epoch(0)

    pbar_main = tqdm(validation_dataloader, desc="Processing batches", disable=not should_log)

    for batch in pbar_main:
        batch_size, sequence_length, view_count = batch["vae_images"].shape[:3]
        origin_dir="/data3/zhoujiawei/carla_nuscenes_benchmark/test_benchmark"
        origin_paths=[
            os.path.join(origin_dir, k["filename"])
            for i in batch["sample_data"]
            for j in i[1:]
            for k in j if not k["filename"].endswith(".bin")
        ]
        latent_height = batch["vae_images"].shape[-2] // \
            (2 ** (len(vae.config.down_block_types) - 1))
        latent_width = batch["vae_images"].shape[-1] // \
            (2 ** (len(vae.config.down_block_types) - 1))
        if "sequence_length_per_iteration" in inference_config:
            latent_shape = (
                batch_size,
                inference_config["sequence_length_per_iteration"],
                view_count, vae.config.latent_channels, latent_height,
                latent_width
            )
            with torch.no_grad():
                pipeline_output = pipeline.autoregressive_inference_pipeline(
                    latent_shape, batch, "pt")
        else:
            latent_shape = (
                batch_size, sequence_length, view_count,
                vae.config.latent_channels, latent_height,
                latent_width
            )
            with torch.no_grad():
                pipeline_output = pipeline.inference_pipeline(latent_shape,batch, "pt")

        if "images" in pipeline_output:
            
            first_6_output_path=[
                os.path.join(args.output_path, k["filename"])
                for i in batch["sample_data"]
                for j in i[:1]
                for k in j if not k["filename"].endswith(".bin")
            ]
            image_results = pipeline_output["images"]  # Shape [222, 3, 256, 448]
            image_sizes = batch["image_size"].flatten(0, 2)[:(6*batch_size)]
            print(len(first_6_output_path))
            print(len(image_results))
            print(len(image_sizes))
            #插入
            for path, image, image_size in zip(first_6_output_path, image_results, image_sizes):
                dir = os.path.dirname(path)
                os.makedirs(dir, exist_ok=True)
                
                # 处理单个图像，不是整个批次
                if isinstance(image, torch.Tensor):
                    # 确保是单个图像的张量，形状应该是[3, H, W]
                    if image.dim() == 3 and image.shape[0] == 3:  # CHW格式
                        # 转换为PIL图像 (对单个图像使用ToPILImage)
                        image_pil = torchvision.transforms.ToPILImage()(image.cpu())
                    else:
                        raise ValueError(f"Unexpected image tensor shape: {image.shape}")
                else:
                    # 假设image已经是PIL图像
                    image_pil = image
                    
                # 使用PIL的resize方法调整大小
                resized_image = image_pil.resize(tuple(image_size.int().tolist()), Image.BILINEAR)
                # 保存图像
                resized_image.save(path, quality=100)

```
`CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src:externals/waymo-open-dataset/src:externals/TATS/tats/fvd torchrun   --nproc_per_node="1"   --nnodes="1"   --node_rank="0"   --master_addr="127.0.0.1"   --master_port="12356"   /home/zhoujiawei/OpenDWM/src/dwm/export_generation_result_as_nuscenes_data_image_generation_replace_first_frame.py   -c /home/zhoujiawei/OpenDWM/configs/unimlvg/generate_result_as_nuscenes_data_frame_generation.json   -o /data3/zhoujiawei/carla_nuscenes_benchmark/test_benchmark_replace_first_frame`
